all:
	gcc -g -o t01 t01.c
	gcc -g -o t02 t02.c
	gcc -g -o t03 t03.c
	gcc -g -o t04 t04.c
	gcc -g -o t05 t05.c
	gcc -g -o t06 t06.c
	gcc -g -o t07 t07.c
	gcc -g -o t08 t08.c
	gcc -g -o t09 t09.c
	gcc -g -o t10 t10.c
	gcc -g -o t11 t11.c
	gcc -g -o t12 t12.c
	gcc -g -o t13 t13.c
	gcc -g -o t14 t14.c
	gcc -g -o e01 e01.c
	gcc -g -o e02 e02.c

clean:
	rm -rf [te][0-9][0-9]
